#syntax=docker/dockerfile:1
FROM alpine

# パッケージをインストール
RUN apk update && \
    apk --no-cache add git 

# 非rootユーザーを使用
ENV USER zenn
ENV HOME /home/$USER
RUN addgroup -S $USER && \
    adduser -S u 1000 -G $USER $USER && \
    chown -R $USER:$USER $HOME
USER $USER

WORKDIR $HOME

# GitHubにSSH接続するための設定
RUN mkdir -p -m 0700 ~/test && \
    cd test && \
    git clone https://github.com/nematatu/nematatu.github.io.git 
#CMD ["git","clone","https://github.com/nematatu/nematatu.github.io.git"]
# プライベートリポジトリをクローン